Repository qdrant/qdrant-cloud-public-api, pull requests merged in 2025-06, with the labels that each got.

#107 Added missing services to README.md
  README.md
  buf.lock
  gen/go/qdrant/cloud/iam/v1/iam_grpc.pb.go
  gen/python/qdrant/cloud/iam/v1/iam_pb2_grpc.py
  gen/typescript/buf/validate/validate_pb.d.ts
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.d.ts
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.js
  proto/qdrant/cloud/iam/v1/iam.proto
Labels: chore

#108 Align packages service comments to the behaviour
  gen/go/qdrant/cloud/booking/v1/booking.pb.go
  gen/openapiv2/qdrant/cloud/booking/v1/booking.swagger.json
  gen/python/qdrant/cloud/booking/v1/booking_pb2.py
  gen/typescript/qdrant/cloud/booking/v1/booking_pb.d.ts
  gen/typescript/qdrant/cloud/booking/v1/booking_pb.js
  proto/qdrant/cloud/booking/v1/booking.proto
Labels: buf skip breaking, chore

#110 Update `AccountService`
  gen/go/qdrant/cloud/account/v1/account.pb.go
  gen/openapiv2/qdrant/cloud/account/v1/account.swagger.json
  gen/python/qdrant/cloud/account/v1/account_pb2.py
  gen/python/qdrant/cloud/account/v1/account_pb2.pyi
  gen/typescript/qdrant/cloud/account/v1/account_pb.d.ts
  gen/typescript/qdrant/cloud/account/v1/account_pb.js
  proto/qdrant/cloud/account/v1/account.proto
Labels: buf skip breaking, chore

#113 Remove user name field from User message
  gen/go/qdrant/cloud/iam/v1/iam.pb.go
  gen/openapiv2/qdrant/cloud/account/v1/account.swagger.json
  gen/openapiv2/qdrant/cloud/iam/v1/iam.swagger.json
  gen/python/qdrant/cloud/iam/v1/iam_pb2.py
  gen/python/qdrant/cloud/iam/v1/iam_pb2.pyi
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.d.ts
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.js
  proto/qdrant/cloud/iam/v1/iam.proto
Labels: buf skip breaking, fix

#116 Update API comments to use consistent verb tense
  gen/go/qdrant/cloud/auth/v1/auth_grpc.pb.go
  gen/go/qdrant/cloud/booking/v1/booking_grpc.pb.go
  gen/go/qdrant/cloud/cluster/auth/v1/database_api_key_grpc.pb.go
  gen/go/qdrant/cloud/cluster/auth/v2/database_api_key_grpc.pb.go
  gen/go/qdrant/cloud/cluster/backup/v1/backup_grpc.pb.go
  gen/go/qdrant/cloud/cluster/v1/cluster_grpc.pb.go
  gen/go/qdrant/cloud/hybrid/v1/hybrid_cloud_grpc.pb.go
  gen/go/qdrant/cloud/monitoring/v1/monitoring_grpc.pb.go
  gen/go/qdrant/cloud/platform/v1/platform_grpc.pb.go
  gen/openapiv2/qdrant/cloud/auth/v1/auth.swagger.json
  gen/openapiv2/qdrant/cloud/booking/v1/booking.swagger.json
  gen/openapiv2/qdrant/cloud/cluster/auth/v1/database_api_key.swagger.json
  gen/openapiv2/qdrant/cloud/cluster/auth/v2/database_api_key.swagger.json
  gen/openapiv2/qdrant/cloud/cluster/backup/v1/backup.swagger.json
  gen/openapiv2/qdrant/cloud/cluster/v1/cluster.swagger.json
  gen/openapiv2/qdrant/cloud/hybrid/v1/hybrid_cloud.swagger.json
  gen/openapiv2/qdrant/cloud/monitoring/v1/monitoring.swagger.json
  gen/openapiv2/qdrant/cloud/platform/v1/platform.swagger.json
  gen/python/qdrant/cloud/auth/v1/auth_pb2_grpc.py
  gen/python/qdrant/cloud/booking/v1/booking_pb2_grpc.py
  gen/python/qdrant/cloud/cluster/auth/v1/database_api_key_pb2_grpc.py
  gen/python/qdrant/cloud/cluster/auth/v2/database_api_key_pb2_grpc.py
  gen/python/qdrant/cloud/cluster/backup/v1/backup_pb2_grpc.py
  gen/python/qdrant/cloud/cluster/v1/cluster_pb2_grpc.py
  gen/python/qdrant/cloud/hybrid/v1/hybrid_cloud_pb2_grpc.py
  gen/python/qdrant/cloud/monitoring/v1/monitoring_pb2_grpc.py
  gen/python/qdrant/cloud/platform/v1/platform_pb2_grpc.py
  gen/typescript/qdrant/cloud/auth/v1/auth_pb.d.ts
  gen/typescript/qdrant/cloud/booking/v1/booking_pb.d.ts
  gen/typescript/qdrant/cloud/cluster/auth/v1/database_api_key_pb.d.ts
  gen/typescript/qdrant/cloud/cluster/auth/v2/database_api_key_pb.d.ts
  gen/typescript/qdrant/cloud/cluster/backup/v1/backup_pb.d.ts
  gen/typescript/qdrant/cloud/cluster/v1/cluster_pb.d.ts
  gen/typescript/qdrant/cloud/hybrid/v1/hybrid_cloud_pb.d.ts
  gen/typescript/qdrant/cloud/monitoring/v1/monitoring_pb.d.ts
  gen/typescript/qdrant/cloud/platform/v1/platform_pb.d.ts
  proto/qdrant/cloud/auth/v1/auth.proto
  proto/qdrant/cloud/booking/v1/booking.proto
  proto/qdrant/cloud/cluster/auth/v1/database_api_key.proto
  proto/qdrant/cloud/cluster/auth/v2/database_api_key.proto
  proto/qdrant/cloud/cluster/backup/v1/backup.proto
  proto/qdrant/cloud/cluster/v1/cluster.proto
  proto/qdrant/cloud/hybrid/v1/hybrid_cloud.proto
  proto/qdrant/cloud/monitoring/v1/monitoring.proto
  proto/qdrant/cloud/platform/v1/platform.proto
Labels: chore

#119 Add ListUserRoles RPC and associated request/response messages
  gen/go/qdrant/cloud/iam/v1/iam.pb.go
  gen/go/qdrant/cloud/iam/v1/iam_grpc.pb.go
  gen/openapiv2/qdrant/cloud/iam/v1/iam.swagger.json
  gen/python/qdrant/cloud/iam/v1/iam_pb2.py
  gen/python/qdrant/cloud/iam/v1/iam_pb2.pyi
  gen/python/qdrant/cloud/iam/v1/iam_pb2_grpc.py
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.d.ts
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.js
  proto/qdrant/cloud/iam/v1/iam.proto
Labels: feature

#121 Add `supported_actor_types` option to more methods
  buf.lock
  gen/go/qdrant/cloud/account/v1/account.pb.go
  gen/go/qdrant/cloud/iam/v1/iam.pb.go
  gen/python/qdrant/cloud/account/v1/account_pb2.py
  gen/python/qdrant/cloud/iam/v1/iam_pb2.py
  gen/typescript/buf/validate/validate_pb.d.ts
  gen/typescript/buf/validate/validate_pb.js
  gen/typescript/qdrant/cloud/account/v1/account_pb.js
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.js
  proto/qdrant/cloud/account/v1/account.proto
  proto/qdrant/cloud/iam/v1/iam.proto
Labels: chore

#122 Add `supported_actor_types` option to `Account.DeleteAccountMember`
  gen/go/qdrant/cloud/account/v1/account.pb.go
  gen/python/qdrant/cloud/account/v1/account_pb2.py
  gen/typescript/qdrant/cloud/account/v1/account_pb.js
  proto/qdrant/cloud/account/v1/account.proto
Labels: chore

#123 Remove user notification preferences from user message
  gen/go/qdrant/cloud/iam/v1/iam.pb.go
  gen/openapiv2/qdrant/cloud/account/v1/account.swagger.json
  gen/openapiv2/qdrant/cloud/iam/v1/iam.swagger.json
  gen/python/qdrant/cloud/iam/v1/iam_pb2.py
  gen/python/qdrant/cloud/iam/v1/iam_pb2.pyi
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.d.ts
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.js
  proto/qdrant/cloud/iam/v1/iam.proto
Labels: buf skip breaking, chore

#124 Create message for user consent
  gen/go/qdrant/cloud/iam/v1/iam.pb.go
  gen/openapiv2/qdrant/cloud/account/v1/account.swagger.json
  gen/openapiv2/qdrant/cloud/iam/v1/iam.swagger.json
  gen/python/qdrant/cloud/iam/v1/iam_pb2.py
  gen/python/qdrant/cloud/iam/v1/iam_pb2.pyi
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.d.ts
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.js
  proto/qdrant/cloud/iam/v1/iam.proto
Labels: buf skip breaking, fix

#125 [CP-199] Update validations for `AccountService.Account`
  gen/go/qdrant/cloud/account/v1/account.pb.go
  gen/openapiv2/qdrant/cloud/account/v1/account.swagger.json
  gen/python/qdrant/cloud/account/v1/account_pb2.py
  gen/python/qdrant/cloud/account/v1/account_pb2.pyi
  gen/typescript/qdrant/cloud/account/v1/account_pb.d.ts
  gen/typescript/qdrant/cloud/account/v1/account_pb.js
  proto/qdrant/cloud/account/v1/account.proto
Labels: buf skip breaking, fix
