Repository qdrant/qdrant-cloud-public-api, pull requests merged in 2025-09, with the labels that each got.

#182 [CP-259] Add new fields to the ClusterConfiguration message
  gen/go/qdrant/cloud/cluster/v1/cluster.pb.go
  gen/openapiv2/qdrant/cloud/cluster/backup/v1/backup.swagger.json
  gen/openapiv2/qdrant/cloud/cluster/v1/cluster.swagger.json
  gen/python/qdrant/cloud/cluster/v1/cluster_pb2.py
  gen/python/qdrant/cloud/cluster/v1/cluster_pb2.pyi
  gen/typescript/qdrant/cloud/cluster/v1/cluster_pb.d.ts
  gen/typescript/qdrant/cloud/cluster/v1/cluster_pb.js
  proto/qdrant/cloud/cluster/v1/cluster.proto
Labels: feature

#186 Update workflows to publish packages for PRs
  .github/actions/publish-packages/action.yml
  .github/actions/shared-setup/action.yml
  .github/workflows/pr-workflow.yaml
  .github/workflows/release-workflow.yaml
Labels: feature

#193 [CP-274] Update validation for Role.name
  buf.lock
  gen/go/qdrant/cloud/iam/v1/iam.pb.go
  gen/openapiv2/qdrant/cloud/iam/v1/iam.swagger.json
  gen/python/qdrant/cloud/iam/v1/iam_pb2.py
  gen/typescript/buf/validate/validate_pb.d.ts
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.d.ts
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.js
  proto/qdrant/cloud/iam/v1/iam.proto
Labels: fix

#189 Add specification for discounts endpoint
  .github/actions/spelling/expect.txt
  gen/go/qdrant/cloud/billing/v1/billing.pb.go
  gen/go/qdrant/cloud/billing/v1/billing_grpc.pb.go
  gen/openapiv2/qdrant/cloud/billing/v1/billing.swagger.json
  gen/python/qdrant/cloud/billing/v1/billing_pb2.py
  gen/python/qdrant/cloud/billing/v1/billing_pb2.pyi
  gen/python/qdrant/cloud/billing/v1/billing_pb2_grpc.py
  gen/typescript/qdrant/cloud/billing/v1/billing-BillingService_connectquery.d.ts
  gen/typescript/qdrant/cloud/billing/v1/billing-BillingService_connectquery.js
  gen/typescript/qdrant/cloud/billing/v1/billing_pb.d.ts
  gen/typescript/qdrant/cloud/billing/v1/billing_pb.js
  proto/qdrant/cloud/billing/v1/billing.proto
Labels: feature

#194 [CP-267] Add new UIViewService
  gen/go/qdrant/cloud/ui/v1/ui.pb.go
  gen/go/qdrant/cloud/ui/v1/ui_grpc.pb.go
  gen/openapiv2/qdrant/cloud/ui/v1/ui.swagger.json
  gen/python/qdrant/cloud/ui/v1/ui_pb2.py
  gen/python/qdrant/cloud/ui/v1/ui_pb2.pyi
  gen/python/qdrant/cloud/ui/v1/ui_pb2_grpc.py
  gen/typescript/qdrant/cloud/ui/v1/ui-UIViewService_connectquery.d.ts
  gen/typescript/qdrant/cloud/ui/v1/ui-UIViewService_connectquery.js
  gen/typescript/qdrant/cloud/ui/v1/ui_pb.d.ts
  gen/typescript/qdrant/cloud/ui/v1/ui_pb.js
  proto/qdrant/cloud/ui/v1/ui.proto
Labels: feature

#195 Rename UIViewService to AggregationService
  gen/go/qdrant/cloud/ui/v1/ui.pb.go
  gen/go/qdrant/cloud/ui/v1/ui_grpc.pb.go
  gen/openapiv2/qdrant/cloud/ui/v1/ui.swagger.json
  gen/python/qdrant/cloud/ui/v1/ui_pb2.py
  gen/python/qdrant/cloud/ui/v1/ui_pb2_grpc.py
  gen/typescript/qdrant/cloud/ui/v1/ui-AggregationService_connectquery.d.ts
  gen/typescript/qdrant/cloud/ui/v1/ui-AggregationService_connectquery.js
  gen/typescript/qdrant/cloud/ui/v1/ui_pb.d.ts
  gen/typescript/qdrant/cloud/ui/v1/ui_pb.js
  proto/qdrant/cloud/ui/v1/ui.proto
Labels: buf skip breaking, chore
