Repository qdrant/qdrant-cloud-public-api, pull requests merged in 2025-08, with the labels that each got.

#153 [BREAKING] Resolved todo
  gen/go/qdrant/cloud/serverless/collection/auth/v1/collection_api_key.pb.go
  gen/openapiv2/qdrant/cloud/serverless/collection/auth/v1/collection_api_key.swagger.json
  gen/python/qdrant/cloud/serverless/collection/auth/v1/collection_api_key_pb2.py
  gen/python/qdrant/cloud/serverless/collection/auth/v1/collection_api_key_pb2.pyi
  gen/typescript/qdrant/cloud/serverless/collection/auth/v1/collection_api_key_pb.d.ts
  gen/typescript/qdrant/cloud/serverless/collection/auth/v1/collection_api_key_pb.js
  proto/qdrant/cloud/serverless/collection/auth/v1/collection_api_key.proto
Labels: buf skip breaking, fix

#157 Added missing validations for BookingService
  gen/go/qdrant/cloud/booking/v1/booking.pb.go
  gen/openapiv2/qdrant/cloud/booking/v1/booking.swagger.json
  gen/python/qdrant/cloud/booking/v1/booking_pb2.py
  gen/typescript/qdrant/cloud/booking/v1/booking_pb.d.ts
  gen/typescript/qdrant/cloud/booking/v1/booking_pb.js
  proto/qdrant/cloud/booking/v1/booking.proto
Labels: chore

#158 Add `PackageTier`
  gen/go/qdrant/cloud/booking/v1/booking.pb.go
  gen/openapiv2/qdrant/cloud/booking/v1/booking.swagger.json
  gen/python/qdrant/cloud/booking/v1/booking_pb2.py
  gen/python/qdrant/cloud/booking/v1/booking_pb2.pyi
  gen/typescript/qdrant/cloud/booking/v1/booking_pb.d.ts
  gen/typescript/qdrant/cloud/booking/v1/booking_pb.js
  proto/qdrant/cloud/booking/v1/booking.proto
Labels: feature

#161 Update Package.Name min 4 -->3 chars
  gen/go/qdrant/cloud/booking/v1/booking.pb.go
  gen/python/qdrant/cloud/booking/v1/booking_pb2.py
  gen/typescript/qdrant/cloud/booking/v1/booking_pb.js
  proto/qdrant/cloud/booking/v1/booking.proto
  proto/qdrant/cloud/common/v1/common.proto
Labels: chore

#163 DatabaseApiKey.email can be empty, or is a valid email address
  gen/go/qdrant/cloud/cluster/auth/v2/database_api_key.pb.go
  gen/openapiv2/qdrant/cloud/cluster/auth/v2/database_api_key.swagger.json
  gen/python/qdrant/cloud/cluster/auth/v2/database_api_key_pb2.py
  gen/typescript/qdrant/cloud/cluster/auth/v2/database_api_key_pb.d.ts
  gen/typescript/qdrant/cloud/cluster/auth/v2/database_api_key_pb.js
  proto/qdrant/cloud/cluster/auth/v2/database_api_key.proto
Labels: fix

#166 Small validation improvements
  gen/go/qdrant/cloud/cluster/auth/v2/database_api_key.pb.go
  gen/go/qdrant/cloud/serverless/collection/auth/v1/collection_api_key.pb.go
  gen/openapiv2/qdrant/cloud/serverless/collection/auth/v1/collection_api_key.swagger.json
  gen/python/qdrant/cloud/cluster/auth/v2/database_api_key_pb2.py
  gen/python/qdrant/cloud/serverless/collection/auth/v1/collection_api_key_pb2.py
  gen/typescript/qdrant/cloud/cluster/auth/v2/database_api_key_pb.js
  gen/typescript/qdrant/cloud/serverless/collection/auth/v1/collection_api_key_pb.d.ts
  gen/typescript/qdrant/cloud/serverless/collection/auth/v1/collection_api_key_pb.js
  proto/qdrant/cloud/cluster/auth/v2/database_api_key.proto
  proto/qdrant/cloud/serverless/collection/auth/v1/collection_api_key.proto
Labels: chore

#175 feat(cluster): add optional package_id to CreateClusterFromBackupRequest
  gen/go/qdrant/cloud/cluster/v1/cluster.pb.go
  gen/openapiv2/qdrant/cloud/cluster/v1/cluster.swagger.json
  gen/python/qdrant/cloud/cluster/v1/cluster_pb2.py
  gen/python/qdrant/cloud/cluster/v1/cluster_pb2.pyi
  gen/typescript/qdrant/cloud/cluster/v1/cluster_pb.d.ts
  gen/typescript/qdrant/cloud/cluster/v1/cluster_pb.js
  proto/qdrant/cloud/cluster/v1/cluster.proto
Labels: feature

#179 Sets the name of the tag to the release version
  .github/workflows/release-workflow.yaml
Labels: chore

#180 Fix: Remove incorrect account_id_expression for GetRole
  gen/go/qdrant/cloud/iam/v1/iam.pb.go
  gen/python/qdrant/cloud/iam/v1/iam_pb2.py
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.js
  proto/qdrant/cloud/iam/v1/iam.proto
Labels: fix
