Repository qdrant/qdrant-cloud-public-api, pull requests merged in 2025-07, with the labels that each got.

#126 Improve the CEL for checking both Global and Collection access in a DatabaseApiKey (v2).
  gen/go/qdrant/cloud/cluster/auth/v2/database_api_key.pb.go
  gen/python/qdrant/cloud/cluster/auth/v2/database_api_key_pb2.py
  gen/typescript/qdrant/cloud/cluster/auth/v2/database_api_key_pb.js
  proto/qdrant/cloud/cluster/auth/v2/database_api_key.proto
Labels: chore

#129 Fix/toni/cleanup js comments
  gen/typescript/qdrant/cloud/booking/v1/booking-BookingService_connectquery.js
  gen/typescript/qdrant/cloud/platform/v1/platform-PlatformService_connectquery.js
  scripts/cleanup-gencode-comments.sh
Labels: fix

#130 Switch to newer generator buf.build/connectrpc/query-es
  buf.gen.yaml
  gen/typescript/qdrant/cloud/account/v1/account-AccountService_connectquery.d.ts
  gen/typescript/qdrant/cloud/account/v1/account-AccountService_connectquery.js
  gen/typescript/qdrant/cloud/auth/v1/auth-AuthService_connectquery.d.ts
  gen/typescript/qdrant/cloud/auth/v1/auth-AuthService_connectquery.js
  gen/typescript/qdrant/cloud/booking/v1/booking-BookingService_connectquery.d.ts
  gen/typescript/qdrant/cloud/booking/v1/booking-BookingService_connectquery.js
  gen/typescript/qdrant/cloud/cluster/auth/v1/database_api_key-DatabaseApiKeyService_connectquery.d.ts
  gen/typescript/qdrant/cloud/cluster/auth/v1/database_api_key-DatabaseApiKeyService_connectquery.js
  gen/typescript/qdrant/cloud/cluster/auth/v2/database_api_key-DatabaseApiKeyService_connectquery.d.ts
  gen/typescript/qdrant/cloud/cluster/auth/v2/database_api_key-DatabaseApiKeyService_connectquery.js
  gen/typescript/qdrant/cloud/cluster/backup/v1/backup-BackupService_connectquery.d.ts
  gen/typescript/qdrant/cloud/cluster/backup/v1/backup-BackupService_connectquery.js
  gen/typescript/qdrant/cloud/cluster/v1/cluster-ClusterService_connectquery.d.ts
  gen/typescript/qdrant/cloud/cluster/v1/cluster-ClusterService_connectquery.js
  gen/typescript/qdrant/cloud/hybrid/v1/hybrid_cloud-HybridCloudService_connectquery.d.ts
  gen/typescript/qdrant/cloud/hybrid/v1/hybrid_cloud-HybridCloudService_connectquery.js
  gen/typescript/qdrant/cloud/iam/v1/iam-IAMService_connectquery.d.ts
  gen/typescript/qdrant/cloud/iam/v1/iam-IAMService_connectquery.js
  gen/typescript/qdrant/cloud/monitoring/v1/monitoring-MonitoringService_connectquery.d.ts
  gen/typescript/qdrant/cloud/monitoring/v1/monitoring-MonitoringService_connectquery.js
  gen/typescript/qdrant/cloud/platform/v1/platform-PlatformService_connectquery.d.ts
  gen/typescript/qdrant/cloud/platform/v1/platform-PlatformService_connectquery.js
  gen/typescript/qdrant/cloud/serverless/collection/auth/v1/collection_api_key-CollectionApiKeyService_connectquery.d.ts
  gen/typescript/qdrant/cloud/serverless/collection/auth/v1/collection_api_key-CollectionApiKeyService_connectquery.js
  gen/typescript/qdrant/cloud/serverless/collection/v1/collection-CollectionService_connectquery.d.ts
  gen/typescript/qdrant/cloud/serverless/collection/v1/collection-CollectionService_connectquery.js
  package.example.json
Labels: fix

#132 Fix the Role validation.
  gen/go/qdrant/cloud/iam/v1/iam.pb.go
  gen/python/qdrant/cloud/iam/v1/iam_pb2.py
  gen/typescript/qdrant/cloud/iam/v1/iam_pb.js
  proto/qdrant/cloud/iam/v1/iam.proto
Labels: fix

#134 Publish `k8s.io` files as the part of typescript package
  package.example.json
Labels: fix

#133 Generate package.json with 'version' and 'exports' fields using shell script
  .github/actions/shared-setup/action.yml
  .gitignore
  package.example.json
  scripts/generate-package-json.sh
Labels: chore

#135 Fix path to script to generate package json in shared action
  .github/actions/shared-setup/action.yml
Labels: chore, fix

#137 Add check `npm view` before uploading node.js pkg
  .github/workflows/release-workflow.yaml
Labels: chore

#127 CF-958: Comprenhensive quota system for account and auth user
  gen/go/qdrant/cloud/quota/v1/quota.pb.go
  gen/go/qdrant/cloud/quota/v1/quota_grpc.pb.go
  gen/openapiv2/qdrant/cloud/quota/v1/quota.swagger.json
  gen/python/qdrant/cloud/quota/v1/quota_pb2.py
  gen/python/qdrant/cloud/quota/v1/quota_pb2.pyi
  gen/python/qdrant/cloud/quota/v1/quota_pb2_grpc.py
  gen/typescript/qdrant/cloud/quota/v1/quota-QuotaService_connectquery.d.ts
  gen/typescript/qdrant/cloud/quota/v1/quota-QuotaService_connectquery.js
  gen/typescript/qdrant/cloud/quota/v1/quota_pb.d.ts
  gen/typescript/qdrant/cloud/quota/v1/quota_pb.js
  proto/qdrant/cloud/quota/v1/quota.proto
Labels: feature

#140 New quota_type max_free_tier_clusters to replace privilege
  gen/go/qdrant/cloud/quota/v1/quota.pb.go
  gen/openapiv2/qdrant/cloud/quota/v1/quota.swagger.json
  gen/python/qdrant/cloud/quota/v1/quota_pb2.py
  gen/python/qdrant/cloud/quota/v1/quota_pb2.pyi
  gen/typescript/qdrant/cloud/quota/v1/quota_pb.d.ts
  gen/typescript/qdrant/cloud/quota/v1/quota_pb.js
  proto/qdrant/cloud/quota/v1/quota.proto
Labels: feature

#131 Add PaymentService
  .github/actions/spelling/allow.txt
  gen/go/qdrant/cloud/payment/v1/payment.pb.go
  gen/go/qdrant/cloud/payment/v1/payment_grpc.pb.go
  gen/openapiv2/qdrant/cloud/payment/v1/payment.swagger.json
  gen/python/qdrant/cloud/payment/v1/payment_pb2.py
  gen/python/qdrant/cloud/payment/v1/payment_pb2.pyi
  gen/python/qdrant/cloud/payment/v1/payment_pb2_grpc.py
  gen/typescript/qdrant/cloud/payment/v1/payment_pb.d.ts
  gen/typescript/qdrant/cloud/payment/v1/payment_pb.js
  proto/qdrant/cloud/payment/v1/payment.proto
Labels: feature

#144 Update mods & buf remote packages.
  buf.gen.yaml
  buf.lock
  gen/python/buf/validate/validate_pb2.py
  gen/python/buf/validate/validate_pb2.pyi
  gen/python/k8s/io/api/core/v1/generated_pb2_grpc.py
  gen/python/k8s/io/api/networking/v1/generated_pb2_grpc.py
  gen/python/k8s/io/apimachinery/pkg/api/resource/generated_pb2_grpc.py
  gen/python/k8s/io/apimachinery/pkg/apis/meta/v1/generated_pb2_grpc.py
  gen/python/k8s/io/apimachinery/pkg/runtime/generated_pb2_grpc.py
  gen/python/k8s/io/apimachinery/pkg/runtime/schema/generated_pb2_grpc.py
  gen/python/k8s/io/apimachinery/pkg/util/intstr/generated_pb2_grpc.py
  gen/typescript/buf/validate/validate_pb.d.ts
  gen/typescript/buf/validate/validate_pb.js
  gen/typescript/qdrant/cloud/account/v1/account-AccountService_connectquery.d.ts
  gen/typescript/qdrant/cloud/account/v1/account-AccountService_connectquery.js
  gen/typescript/qdrant/cloud/auth/v1/auth-AuthService_connectquery.d.ts
  gen/typescript/qdrant/cloud/auth/v1/auth-AuthService_connectquery.js
  gen/typescript/qdrant/cloud/billing/v1/billing-BillingService_connectquery.d.ts
  gen/typescript/qdrant/cloud/billing/v1/billing-BillingService_connectquery.js
  gen/typescript/qdrant/cloud/booking/v1/booking-BookingService_connectquery.d.ts
  gen/typescript/qdrant/cloud/booking/v1/booking-BookingService_connectquery.js
  gen/typescript/qdrant/cloud/cluster/auth/v1/database_api_key-DatabaseApiKeyService_connectquery.d.ts
  gen/typescript/qdrant/cloud/cluster/auth/v1/database_api_key-DatabaseApiKeyService_connectquery.js
  gen/typescript/qdrant/cloud/cluster/auth/v2/database_api_key-DatabaseApiKeyService_connectquery.d.ts
  gen/typescript/qdrant/cloud/cluster/auth/v2/database_api_key-DatabaseApiKeyService_connectquery.js
  gen/typescript/qdrant/cloud/cluster/backup/v1/backup-BackupService_connectquery.d.ts
  gen/typescript/qdrant/cloud/cluster/backup/v1/backup-BackupService_connectquery.js
  gen/typescript/qdrant/cloud/cluster/v1/cluster-ClusterService_connectquery.d.ts
  gen/typescript/qdrant/cloud/cluster/v1/cluster-ClusterService_connectquery.js
  gen/typescript/qdrant/cloud/hybrid/v1/hybrid_cloud-HybridCloudService_connectquery.d.ts
  gen/typescript/qdrant/cloud/hybrid/v1/hybrid_cloud-HybridCloudService_connectquery.js
  gen/typescript/qdrant/cloud/iam/v1/iam-IAMService_connectquery.d.ts
  gen/typescript/qdrant/cloud/iam/v1/iam-IAMService_connectquery.js
  gen/typescript/qdrant/cloud/metering/v1/metering-MeteringService_connectquery.d.ts
  gen/typescript/qdrant/cloud/metering/v1/metering-MeteringService_connectquery.js
  gen/typescript/qdrant/cloud/monitoring/v1/monitoring-MonitoringService_connectquery.d.ts
  gen/typescript/qdrant/cloud/monitoring/v1/monitoring-MonitoringService_connectquery.js
  gen/typescript/qdrant/cloud/payment/v1/payment-PaymentService_connectquery.d.ts
  gen/typescript/qdrant/cloud/payment/v1/payment-PaymentService_connectquery.js
  gen/typescript/qdrant/cloud/platform/v1/platform-PlatformService_connectquery.d.ts
  gen/typescript/qdrant/cloud/platform/v1/platform-PlatformService_connectquery.js
  gen/typescript/qdrant/cloud/quota/v1/quota-QuotaService_connectquery.d.ts
  gen/typescript/qdrant/cloud/quota/v1/quota-QuotaService_connectquery.js
  gen/typescript/qdrant/cloud/serverless/collection/auth/v1/collection_api_key-CollectionApiKeyService_connectquery.d.ts
  gen/typescript/qdrant/cloud/serverless/collection/auth/v1/collection_api_key-CollectionApiKeyService_connectquery.js
  gen/typescript/qdrant/cloud/serverless/collection/v1/collection-CollectionService_connectquery.d.ts
  gen/typescript/qdrant/cloud/serverless/collection/v1/collection-CollectionService_connectquery.js
  go.mod
  go.sum
Labels: buf skip breaking, chore
